/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SolidityTypes_pb = require('./SolidityTypes_pb.js');
goog.object.extend(proto, SolidityTypes_pb);
goog.exportSymbol('proto.FSPStatus', null, global);
goog.exportSymbol('proto.InstrumentStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.InstrumentStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.InstrumentStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.InstrumentStatus.displayName = 'proto.InstrumentStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FSPStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.FSPStatus.repeatedFields_, null);
};
goog.inherits(proto.FSPStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.FSPStatus.displayName = 'proto.FSPStatus';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.InstrumentStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.InstrumentStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.InstrumentStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.InstrumentStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    instrumentaddress: (f = msg.getInstrumentaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    fspaddress: (f = msg.getFspaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    active: jspb.Message.getFieldWithDefault(msg, 3, false),
    creation: (f = msg.getCreation()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    expiration: (f = msg.getExpiration()) && SolidityTypes_pb.uint256.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.InstrumentStatus}
 */
proto.InstrumentStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.InstrumentStatus;
  return proto.InstrumentStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.InstrumentStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.InstrumentStatus}
 */
proto.InstrumentStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setInstrumentaddress(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setFspaddress(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setActive(value);
      break;
    case 4:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setCreation(value);
      break;
    case 5:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setExpiration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.InstrumentStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.InstrumentStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.InstrumentStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.InstrumentStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInstrumentaddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getFspaddress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getActive();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getCreation();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getExpiration();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
};


/**
 * optional solidity.address instrumentAddress = 1;
 * @return {?proto.solidity.address}
 */
proto.InstrumentStatus.prototype.getInstrumentaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 1));
};


/** @param {?proto.solidity.address|undefined} value */
proto.InstrumentStatus.prototype.setInstrumentaddress = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.InstrumentStatus.prototype.clearInstrumentaddress = function() {
  this.setInstrumentaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.InstrumentStatus.prototype.hasInstrumentaddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional solidity.address fspAddress = 2;
 * @return {?proto.solidity.address}
 */
proto.InstrumentStatus.prototype.getFspaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 2));
};


/** @param {?proto.solidity.address|undefined} value */
proto.InstrumentStatus.prototype.setFspaddress = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.InstrumentStatus.prototype.clearFspaddress = function() {
  this.setFspaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.InstrumentStatus.prototype.hasFspaddress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool active = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.InstrumentStatus.prototype.getActive = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.InstrumentStatus.prototype.setActive = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional solidity.uint256 creation = 4;
 * @return {?proto.solidity.uint256}
 */
proto.InstrumentStatus.prototype.getCreation = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 4));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.InstrumentStatus.prototype.setCreation = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.InstrumentStatus.prototype.clearCreation = function() {
  this.setCreation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.InstrumentStatus.prototype.hasCreation = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional solidity.uint256 expiration = 5;
 * @return {?proto.solidity.uint256}
 */
proto.InstrumentStatus.prototype.getExpiration = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 5));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.InstrumentStatus.prototype.setExpiration = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.InstrumentStatus.prototype.clearExpiration = function() {
  this.setExpiration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.InstrumentStatus.prototype.hasExpiration = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.FSPStatus.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FSPStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.FSPStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FSPStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FSPStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    fspaddress: (f = msg.getFspaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    instrumentaddressesList: jspb.Message.toObjectList(msg.getInstrumentaddressesList(),
    SolidityTypes_pb.address.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FSPStatus}
 */
proto.FSPStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FSPStatus;
  return proto.FSPStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FSPStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FSPStatus}
 */
proto.FSPStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setFspaddress(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.addInstrumentaddresses(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FSPStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FSPStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FSPStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FSPStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFspaddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getInstrumentaddressesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
};


/**
 * optional solidity.address fspAddress = 1;
 * @return {?proto.solidity.address}
 */
proto.FSPStatus.prototype.getFspaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 1));
};


/** @param {?proto.solidity.address|undefined} value */
proto.FSPStatus.prototype.setFspaddress = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.FSPStatus.prototype.clearFspaddress = function() {
  this.setFspaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FSPStatus.prototype.hasFspaddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated solidity.address instrumentAddresses = 2;
 * @return {!Array<!proto.solidity.address>}
 */
proto.FSPStatus.prototype.getInstrumentaddressesList = function() {
  return /** @type{!Array<!proto.solidity.address>} */ (
    jspb.Message.getRepeatedWrapperField(this, SolidityTypes_pb.address, 2));
};


/** @param {!Array<!proto.solidity.address>} value */
proto.FSPStatus.prototype.setInstrumentaddressesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.solidity.address=} opt_value
 * @param {number=} opt_index
 * @return {!proto.solidity.address}
 */
proto.FSPStatus.prototype.addInstrumentaddresses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.solidity.address, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.FSPStatus.prototype.clearInstrumentaddressesList = function() {
  this.setInstrumentaddressesList([]);
};


goog.object.extend(exports, proto);
