/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SolidityTypes_pb = require('./SolidityTypes_pb.js');
goog.object.extend(proto, SolidityTypes_pb);
goog.exportSymbol('proto.CommonProperties', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CommonProperties = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CommonProperties, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CommonProperties.displayName = 'proto.CommonProperties';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CommonProperties.prototype.toObject = function(opt_includeInstance) {
  return proto.CommonProperties.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CommonProperties} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CommonProperties.toObject = function(includeInstance, msg) {
  var f, obj = {
    issuanceid: (f = msg.getIssuanceid()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    instrumentaddress: (f = msg.getInstrumentaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    selleraddress: (f = msg.getSelleraddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    storageaddress: (f = msg.getStorageaddress()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    created: (f = msg.getCreated()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    state: (f = msg.getState()) && SolidityTypes_pb.uint256.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CommonProperties}
 */
proto.CommonProperties.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CommonProperties;
  return proto.CommonProperties.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CommonProperties} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CommonProperties}
 */
proto.CommonProperties.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setIssuanceid(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setInstrumentaddress(value);
      break;
    case 3:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setSelleraddress(value);
      break;
    case 4:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setStorageaddress(value);
      break;
    case 5:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setCreated(value);
      break;
    case 6:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CommonProperties.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CommonProperties.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CommonProperties} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CommonProperties.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIssuanceid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getInstrumentaddress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getSelleraddress();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getStorageaddress();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getCreated();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
};


/**
 * optional solidity.uint256 issuanceId = 1;
 * @return {?proto.solidity.uint256}
 */
proto.CommonProperties.prototype.getIssuanceid = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 1));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.CommonProperties.prototype.setIssuanceid = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.CommonProperties.prototype.clearIssuanceid = function() {
  this.setIssuanceid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CommonProperties.prototype.hasIssuanceid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional solidity.address instrumentAddress = 2;
 * @return {?proto.solidity.address}
 */
proto.CommonProperties.prototype.getInstrumentaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 2));
};


/** @param {?proto.solidity.address|undefined} value */
proto.CommonProperties.prototype.setInstrumentaddress = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.CommonProperties.prototype.clearInstrumentaddress = function() {
  this.setInstrumentaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CommonProperties.prototype.hasInstrumentaddress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional solidity.address sellerAddress = 3;
 * @return {?proto.solidity.address}
 */
proto.CommonProperties.prototype.getSelleraddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 3));
};


/** @param {?proto.solidity.address|undefined} value */
proto.CommonProperties.prototype.setSelleraddress = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.CommonProperties.prototype.clearSelleraddress = function() {
  this.setSelleraddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CommonProperties.prototype.hasSelleraddress = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional solidity.address storageAddress = 4;
 * @return {?proto.solidity.address}
 */
proto.CommonProperties.prototype.getStorageaddress = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 4));
};


/** @param {?proto.solidity.address|undefined} value */
proto.CommonProperties.prototype.setStorageaddress = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.CommonProperties.prototype.clearStorageaddress = function() {
  this.setStorageaddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CommonProperties.prototype.hasStorageaddress = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional solidity.uint256 created = 5;
 * @return {?proto.solidity.uint256}
 */
proto.CommonProperties.prototype.getCreated = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 5));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.CommonProperties.prototype.setCreated = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.CommonProperties.prototype.clearCreated = function() {
  this.setCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CommonProperties.prototype.hasCreated = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional solidity.uint256 state = 6;
 * @return {?proto.solidity.uint256}
 */
proto.CommonProperties.prototype.getState = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 6));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.CommonProperties.prototype.setState = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.CommonProperties.prototype.clearState = function() {
  this.setState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CommonProperties.prototype.hasState = function() {
  return jspb.Message.getField(this, 6) != null;
};


goog.object.extend(exports, proto);
